---
version: '2'

services:
  jenkins:
    build: ./jenkins_app
    privileged: true
    networks:
      - jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

networks:
  jenkins:
    driver: bridge
volumes:
  jenkins-data:
    driver: local
  jenkins-docker-certs:
    driver: local
