---
- name: Install 
  hosts: all
  become: yes
  become_method: sudo
  
  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
    - { role: jenkins, tags: jenkins }

  tasks: []
         
    
       